package com.sweetop.styhadoop;

/**
 * Autogenerated by Avro
 * <p/>
 * DO NOT EDIT DIRECTLY
 */
@SuppressWarnings("all")
/** A pair of strings */
public class StringPair extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"com.sweetop.styhadoop.StringPair\",\"doc\":\"A pair of strings\",\"fields\":[{\"name\":\"left\",\"type\":\"string\",\"avro.java.string\":\"String\"},{\"name\":\"right\",\"type\":\"string\"}]}");
    @Deprecated
    public java.lang.CharSequence left;
    @Deprecated
    public java.lang.CharSequence right;

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }

    // Used by DatumWriter.  Applications should not call.
    public java.lang.Object get(int field$) {
        switch (field$) {
            case 0:
                return left;
            case 1:
                return right;
            default:
                throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }

    // Used by DatumReader.  Applications should not call.
    @SuppressWarnings(value = "unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
            case 0:
                left = (java.lang.CharSequence) value$;
                break;
            case 1:
                right = (java.lang.CharSequence) value$;
                break;
            default:
                throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }

    /**
     * Gets the value of the 'left' field.
     */
    public java.lang.CharSequence getLeft() {
        return left;
    }

    /**
     * Sets the value of the 'left' field.
     *
     * @param value the value to set.
     */
    public void setLeft(java.lang.CharSequence value) {
        this.left = value;
    }

    /**
     * Gets the value of the 'right' field.
     */
    public java.lang.CharSequence getRight() {
        return right;
    }

    /**
     * Sets the value of the 'right' field.
     *
     * @param value the value to set.
     */
    public void setRight(java.lang.CharSequence value) {
        this.right = value;
    }
}
